### ISSUE TITLE
Something wrong with url setting

### ISSUE THREAD

**Issue by lony** [davidji99/simpleresty#9]
**Describe the bug**
I used your example from the Readme to try out your lib but could not get it to work. After debugging, I found out that the URL is not set appropriate. After removing the `c.SetBaseURL("https://api.github.com")` line it worked.

**To Reproduce**
Steps to reproduce the behaviour just run

```
package main

import (
	"fmt"

	"github.com/davidji99/simpleresty"
)

type GithubAPIResponse struct {
	CurrentUserURL string `json:"current_user_url,omitempty"`
}

func main() {
	c := simpleresty.New()
	c.SetBaseURL("https://api.github.com") // This causes the error

	var result *GithubAPIResponse
	response, getErr := c.Get("https://api.github.com", &result, nil)

	fmt.Println(getErr)

	fmt.Println(response.StatusCode)
	fmt.Println(result.CurrentUserURL)
	fmt.Println(response.Body)
}
```

**Expected behaviour**
Schema error as URL is just `""` empty string

**Version**

```
module foobar

go 1.14

require github.com/davidji99/simpleresty v0.2.1
```

**Comment by davidji99** [comment]
Oh boy. Thanks for letting me know! Let me fix this.

**Comment by davidji99** [comment]
Done via https://github.com/davidji99/simpleresty/pull/10.
